#!/usr/bin/env bash

INTERFACE=/sys/class/power_supply/BAT0/

percent="$(cat "$INTERFACE/capacity")"

class() {
	if [[ "$percent" -gt 40 ]]; then
		echo "battery--success"
	elif [[ "$percent" -gt 20 ]]; then
		echo "battery--warning"
	else
		echo "battery--danger"
	fi
}

icon() {
	[[ "$(cat "$INTERFACE/status")" = "Charging" ]] && echo "" || echo ""
}

[ "$1" = "percent" ] && echo "$percent" && exit
[ "$1" = "class" ] && class && exit
[ "$1" = "icon" ] && icon && exit
