#!/usr/bin/env bash

TERMINAL=alacritty

case $1 in
    "launcher")
        $HOME/.config/rofi/scripts/appmenu.sh
        ;;
    "torrents")
        $TERMINAL -e tremc
        ;;
    "updates")
        $TERMINAL -e yay -Syu
        ;;
esac
