#!/usr/bin/env bash

set -e

on_change() {
    if [[ "$(cat /sys/class/net/wlp*/operstate)" = "up" ]]; then
        connection="$(nmcli -t -f NAME connection show --active | head -n 1)"
        icon="直"
    else
        connection="No connection"
        icon="睊"
    fi

    case "$(nmcli -g CONNECTIVITY general)" in
        "full")
            class="icon--primary"
            ;;
        "limited")
            class="icon--warning"
            ;;
        "none")
            class="icon--disabled"
            ;;
    esac

    echo "{ \"connection\": \"$connection\", \"class\": \"$class\", \"icon\": \"$icon\" }"
}

on_change
nmcli monitor | while read -r line; do
    if [[ -z "$(echo "$line" | awk '/Connectivity is now/')" ]]; then
        on_change
    fi
done
