config_version = 2

[bar.main]
end = [ "tray", "notifications", "bluetooth", "network", "volume", "battery" ]
margin_edge = 0.0
margin_ends = 60
position = "bottom"
radius_bottom_left = 0
radius_bottom_right = 0
reserve_space = false
smart_auto_hide = true
start = [ "clock", "group:g1" ]
thickness = 40

    [[bar.main.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "ram", "sysmon", "network_rx", "network_tx" ]
    opacity = 0.89999997615814209
    padding = 6.0
    radius = 8.0

[calendar]
enabled = true

    [calendar.account.personal_google]
    name = "Personal"
    type = "google"

[control_center]
sidebar_section = "none"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "noctalia/screen_recorder:toggle"

    [[control_center.shortcuts]]
    type = "mic_mute"

[desktop_widgets]
enabled = true
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 144.0
    box_width = 352.0
    cx = 1744.0
    cy = 72.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        shadow = false

[keybinds]
down = [ "Down", "Ctrl+n" ]
up = [ "Up", "Ctrl+p" ]

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-5",
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@DP-7",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001"
]

    [lockscreen_widgets.grid]
    cell_size = 24
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    box_height = 0.0
    box_width = 0.0
    cx = 1720.0
    cy = 1317.0
    output = "DP-5"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-5".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-7"]
    box_height = 0.0
    box_width = 0.0
    cx = 1720.0
    cy = 1317.0
    output = "DP-7"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-7".settings]
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1720.0
    cy = 1317.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 639.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        show_login_button = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 160.0
    box_width = 368.0
    cx = 960.0
    cy = 504.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        color = "primary"
        font_family = "Rubik"

[notification]
blacklist = [ "discord" ]

[plugin_settings."noctalia/screen_recorder"]
video_codec = "av1"

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/translator" ]

    [[plugins.source]]
    auto_update = true
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
password_style = "random"
settings_show_advanced = true

    [shell.launcher]
    categories = false

    [shell.panel]
    clipboard_position = "top_center"
    control_center_placement = "floating"
    floating_offset = 0
    launcher_categories = false
    launcher_position = "top_center"
    open_near_click_control_center = true
    polkit_position = "top_center"
    session_placement = "floating"
    session_position = "top_center"
    transparency_mode = "soft"
    wallpaper_placement = "floating"
    wallpaper_position = "top_center"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    pipe_command = "satty -f -"
    pipe_to_command = true
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "x"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "p"
    variant = "destructive"

    [[shell.session.actions]]
    action = "suspend"
    enabled = false
    shortcut = "3"
    variant = "default"

[theme]
community_palette = "Catppuccin Lavender"
source = "community"

[wallpaper]
fill_color = "surface"
transition = [ "disc" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/pbaudry/Pictures/Wallpapers/1.jpg"

    [wallpaper.last]
    path = "/home/pbaudry/Pictures/Wallpapers/1.jpg"

[widget.bluetooth]
show_label = true

[widget.clock]
format = "{:%H:%M %a %x}"

[widget.cpu]
display = "text"

[widget.network_rx]
display = "text"

[widget.network_tx]
display = "text"

[widget.notifications]
hide_when_no_unread = true

[widget.ram]
display = "text"
stat = "ram_pct"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.sysmon]
display = "text"
stat = "ram_pct"

[widget.workspaces]
empty_color = "surface"
focused_color = "tertiary"
occupied_color = "primary"
scale = 1.1500000000000001