#!/usr/bin/env bash

set -e

on_change() {
    if [[ -n "$(rfkill list wlan | awk '/Soft blocked: no/')" ]]; then
        icon="直"
    else
        icon="睊"
    fi

    if [[ "$(cat /sys/class/net/wlp*/operstate)" = "up" ]]; then
        connection="$(nmcli -t -f NAME connection show --active | head -n 1)"
    else
        connection="No connection"
    fi

    case "$(nmcli -g CONNECTIVITY general)" in
        "full")
            class="icon--primary--variable"
            ;;
        "limited")
            class="icon--warning--variable"
            ;;
        "none")
            class="icon--disabled--variable"
            ;;
    esac

    echo "{ \"connection\": \"$connection\", \"class\": \"$class\", \"icon\": \"$icon\" }"
}

on_change
nmcli monitor | while read -r line; do
    on_change
done
