#!/usr/bin/env bash

session=$1
session_path=$2

tmux new-window -t "$session" -c "$session_path"
tmux send -t "$session:2.1" -c "$session_path" "lazydocker" Enter
tmux splitw -t "$session:2" -c "$session_path" -h
tmux select-window -t "$session:1"
