local gears = require('gears')

local icons_dir = gears.filesystem.get_configuration_dir() .. 'theme/icons/'

return {
	arrow_down = 'ﰬ',
	arrow_up = 'ﰵ',
	battery_charging = '',
	battery_discharging = '',
	bluetooth_off = '',
	bluetooth_on = '',
	brightness = '',
	chat = '',
	chevron_left = '',
	chevron_right = '',
	chrome = '',
	clock = '',
	code = '',
	download = '',
	ethernet = '',
	files = '',
	games = '',
	layout_floating = icons_dir .. 'layout/floating.svg',
	layout_max = icons_dir .. 'layout/max.svg',
	layout_tiled = icons_dir .. 'layout/tiled.svg',
	lock = '',
	logout = '',
	media = '',
	menu = '',
	pause = '',
	play = '',
	power = '',
	reboot = '',
	skip_next = '',
	skip_previous = '',
	suspend = '',
	terminal = '',
	updates = '',
	upload = '',
	volume_off = '婢',
	volume_on = '墳',
	wifi_off = '睊',
	wifi_on = '直',
}
