#!/usr/bin/env bash

function refresh_wm {
    case "$(wmctrl -m | awk '/Name:/ {print $2}')" in
        "LeftWM") leftwm-command "SoftReload" ;;
        "*") ;;
    esac
}

if [[ -x "$(command -v wmctrl)" ]]; then
    refresh_wm
fi
