hl.config({
  animations = { enabled = true },
})

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.1, 0 }, { 0.0, 1 } } })

hl.curve("spring", { type = "spring", mass = 1, stiffness = 80, dampening = 10 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5, bezier = "almostLinear" })
hl.animation({ leaf = "windows", enabled = true, speed = 15, spring = "spring", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 15, spring = "spring", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 15, spring = "spring", style = "slide bottom" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 15, spring = "spring" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 3, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 2, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 4, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 5, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 1, bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1, bezier = "linear", style = "slide" })
hl.animation({ leaf = "fadeLayersIn", enabled = false, speed = 3, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = false, speed = 2, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 15, spring = "spring", style = "slidevert" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 15, spring = "spring", style = "slidevert" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 15, spring = "spring", style = "slidevert" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 10, bezier = "quick" })
