#!/usr/bin/env bash

set -e

DEVICE="$1"

# Exit script if no device
if [[ -z $DEVICE ]]; then
    exit
fi

on_change() {
    icon=""
    connection=""

    if [[ "$(cat /sys/class/net/$DEVICE/operstate)" = "up" ]]; then
        class="icon--primary--variable"
        connection="$(nmcli -t connection show --active | awk -F ':' -v device=$DEVICE '$0~device { print $1 }')"
    else
        class="icon--disabled--variable"
    fi

    echo "{ \"device\": \"$DEVICE\", \"connection\": \"$connection\", \"class\": \"$class\", \"icon\": \"$icon\" }"
}

on_change
nmcli monitor | while read -r line
do
    on_change
done
