#!/usr/bin/env bash

TERMINAL=alacritty

case $1 in
    "bluetooth")
        blueman-manager
        ;;
    "launcher")
        $HOME/.config/rofi/scripts/appmenu.sh
        ;;
    "network")
        $TERMINAL -e nmtui
        ;;
    "torrents")
        $TERMINAL -e tremc
        ;;
    "tray")
        trayer --edge top --align right --distance 44 --widthtype pixel --width 80 --heighttype request --padding 8 --tint 0x00FF00FF
        ;;
    "updates")
        $TERMINAL -e bash -c "paru -Syu; echo Done - Press enter to exit...; read _"
        ;;
    "volume")
        pavucontrol
        ;;
esac
