#!/usr/bin/env bash

set -e

on_change() {
    percent=$(amixer -D pulse sget Master | awk -F '[][%]' '/\[.*%\]/ {print $2; exit}')

    if [[ $percent -ge 50 ]]; then
        icon="墳"
    elif [[ $percent -gt 0 ]]; then
        icon="奔"
    else
        icon="奄"
    fi

    if [[ $(amixer -D pulse sget Master | awk -F '[][]' '/\[.*%\]/ {print $4; exit}') = "on" ]]; then
        muted="false"
    else
        muted="true"
        icon="婢"
    fi

    echo "{ \"percent\": $percent, \"muted\": $muted, \"icon\": \"$icon\" }"
}

on_change
pactl subscribe | while read -r line; do
    if [[ "$line" = "Event 'change' on sink"* ]]; then
        on_change
    fi
done
